name: build template
on: [push]

jobs:
  build:
    name: build and update template
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up Python 3.6.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.9
    - name: install pdflatex
      run: sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
    - name: build template
      run: |
        cd atl
        python gen.py
        cd ..
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: commit file
      run: |
        git add atl/temp.pdf
        git commit -m "update temp.pdf"
        git push origin master
